### ISSUE TITLE
Can we have EEM Project Plan to include the PI and Sprint Numbers in assignments window?

### ISSUE THREAD

**Issue by EagleLabs** [EagleShare/EEM#1]
The current assignments are done thru the Project Plan tool and we are referring to the Excel to get the right tasks to assign. If we can get the PI and Sprint custom fields on the PP assignments window it will be easy for Scrum Masters to refer to. 
![pi and sprint numbers](https://user-images.githubusercontent.com/36397349/36140311-c19f7988-1098-11e8-95cc-121e61bf0136.PNG)

**Comment by EagleShare** [comment]
- This requires you to setup the configuration for the custom field columns to be shown in assign window.
- Use the System Preferences screen, Application tab to make the required change
- Please select the custom fields that needs to be shown in the Project Plan assignment window.
