### ISSUE TITLE
Export to excel is not working in the request when we have sprint numbers and Program Increment 

### ISSUE THREAD

**Issue by ShivaprakashHombaiah** [EagleShare/EEM#11]
Export to excel is not working when we have the fields (Program Increment and Sprint nos) in the request 
Make sure we need to support Program Increment /Sprint Numbers

**Comment by EagleShare** [comment]
It was seen when the custom fields column is selected and export to excel is done in RT. Then it was not working because of the long description for custom fields was not handled. Its fixed now in the latest release.
