### ISSUE TITLE
EEM Absence Notification thru EEM Website logs in Leave as 0.5 day. I have not checked it thru the Site thou.

### ISSUE THREAD

**Issue by ShivaprakashHombaiah** [EagleShare/EEM#17]
Users are provided with an option to register their leave/permissions thru EEM from Internet. When users apply for leave, even though they select more than 4 hours and it asks if this can be applied as leave, it registers only 0.5 day.

**Comment by EagleShare** [comment]
In the latest release Allowed hours of permission is taken from externalized value. Applying half day is not allowed.

**Comment by EagleShare** [comment]
In the latest release Allowed hours of permission is taken from externalized value. Applying half day is not allowed.
