### ISSUE TITLE
Can we have a new report to identify the tasks assigned are not planned for the current sprint? This will also inlcude the ones that are supposed to be assigned in that sprint.

### ISSUE THREAD

**Issue by EagleLabs** [EagleShare/EEM#2]
[Report to get tasks that are wrongly assigned in the Sprint.docx](https://github.com/EagleShare/EEM/files/1730575/Report.to.get.tasks.that.are.wrongly.assigned.in.the.Sprint.docx)

**Comment by EagleShare** [comment]
The above task mentioned doesn't require any report. This can be achieved by setting up a filter in the request tracker with the conditions mentioned as described in the task. We are supporting the filter of custom fields in request tracker, thus it helps you to filter the tasks that are assigned but not in current sprint also the tasks that are not assigned but in the current sprint.  For any further queries please feel free to comment back.
